version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: postgres_hiring
    environment:
      POSTGRES_DB: hiring_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: hiring_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hiring_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres